/**
 * HTML export utilities for generating printable "Sale Pack" reports
 */

import { CarEvent, Vehicle, Attachment } from '../types';
import { loadEvents, loadVehicleProfile } from './storage';

export interface ExportOptions {
  includeAllEvents?: boolean;
  maxEvents?: number;
  includeAttachments?: boolean;
  title?: string;
}

/**
 * Generate HTML export for vehicle sale pack
 */
export function generateSalePackHTML(options: ExportOptions = {}): string {
  const {
    includeAllEvents = false,
    maxEvents = 20,
    includeAttachments = true,
    title = 'Vehicle Sale Pack'
  } = options;

  const vehicleProfile = loadVehicleProfile();
  const allEvents = loadEvents();
  
  // Get recent events (sorted by date, newest first)
  const events = includeAllEvents 
    ? allEvents 
    : allEvents
        .sort((a, b) => new Date(b.occurredAt).getTime() - new Date(a.occurredAt).getTime())
        .slice(0, maxEvents);

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${escapeHtml(title)}</title>
    <style>
        ${getExportCSS()}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>${escapeHtml(title)}</h1>
            <p class="export-date">Generated on ${new Date().toLocaleDateString()}</p>
        </header>

        ${generateVehicleSection(vehicleProfile, includeAttachments)}
        ${generateEventsSection(events, includeAttachments)}
        ${generateSummarySection(allEvents)}
        
        <footer class="footer">
            <p>Generated by Car Journal - ${new Date().toLocaleString()}</p>
        </footer>
    </div>
</body>
</html>`;

  return html;
}

/**
 * Generate vehicle profile section
 */
function generateVehicleSection(vehicle: Vehicle | null, includeAttachments: boolean): string {
  if (!vehicle) {
    return `
        <section class="vehicle-section">
            <h2>Vehicle Information</h2>
            <p class="no-data">No vehicle profile available</p>
        </section>
    `;
  }

  const photos = includeAttachments ? vehicle.photos : [];

  return `
        <section class="vehicle-section">
            <h2>Vehicle Information</h2>
            <div class="vehicle-grid">
                <div class="vehicle-details">
                    ${vehicle.make ? `<div class="detail-row"><strong>Make:</strong> ${escapeHtml(vehicle.make)}</div>` : ''}
                    ${vehicle.model ? `<div class="detail-row"><strong>Model:</strong> ${escapeHtml(vehicle.model)}</div>` : ''}
                    ${vehicle.vin ? `<div class="detail-row"><strong>VIN:</strong> ${escapeHtml(vehicle.vin)}</div>` : ''}
                    ${vehicle.plate ? `<div class="detail-row"><strong>License Plate:</strong> ${escapeHtml(vehicle.plate)}</div>` : ''}
                    ${vehicle.fuelType ? `<div class="detail-row"><strong>Fuel Type:</strong> ${escapeHtml(vehicle.fuelType)}</div>` : ''}
                    ${vehicle.purchasedOn ? `<div class="detail-row"><strong>Purchase Date:</strong> ${new Date(vehicle.purchasedOn).toLocaleDateString()}</div>` : ''}
                    ${vehicle.notes ? `<div class="detail-row"><strong>Notes:</strong> ${escapeHtml(vehicle.notes)}</div>` : ''}
                </div>
                ${photos.length > 0 ? `
                <div class="vehicle-photos">
                    <h3>Vehicle Photos</h3>
                    <div class="photo-grid">
                        ${photos.map(photo => generateAttachmentHTML(photo, true)).join('')}
                    </div>
                </div>
                ` : ''}
            </div>
        </section>
    `;
}

/**
 * Generate events section
 */
function generateEventsSection(events: CarEvent[], includeAttachments: boolean): string {
  if (events.length === 0) {
    return `
        <section class="events-section">
            <h2>Maintenance & Service History</h2>
            <p class="no-data">No events recorded</p>
        </section>
    `;
  }

  return `
        <section class="events-section">
            <h2>Maintenance & Service History</h2>
            <div class="events-list">
                ${events.map(event => generateEventHTML(event, includeAttachments)).join('')}
            </div>
        </section>
    `;
}

/**
 * Generate individual event HTML
 */
function generateEventHTML(event: CarEvent, includeAttachments: boolean): string {
  const typeColors: Record<string, string> = {
    fuel: '#10b981',
    service: '#3b82f6',
    tires: '#8b5cf6',
    damage: '#ef4444',
    obd: '#f59e0b',
    custom: '#6b7280'
  };

  const typeColor = typeColors[event.type] || '#6b7280';
  const attachments = includeAttachments ? event.attachments : [];

  return `
        <div class="event-card">
            <div class="event-header">
                <div class="event-type" style="background-color: ${typeColor}">
                    ${escapeHtml(event.type)}
                </div>
                <div class="event-date">${new Date(event.occurredAt).toLocaleDateString()}</div>
                ${event.mileageKm ? `<div class="event-mileage">${event.mileageKm.toLocaleString()} km</div>` : ''}
            </div>
            
            <h3 class="event-title">${escapeHtml(event.title)}</h3>
            
            ${event.notes ? `<p class="event-notes">${escapeHtml(event.notes)}</p>` : ''}
            
            ${event.tags.length > 0 ? `
            <div class="event-tags">
                ${event.tags.map(tag => `<span class="tag">#${escapeHtml(tag)}</span>`).join('')}
            </div>
            ` : ''}
            
            ${generateEventTypeSpecificFields(event)}
            
            ${attachments.length > 0 ? `
            <div class="event-attachments">
                <h4>Attachments</h4>
                <div class="attachment-grid">
                    ${attachments.map(attachment => generateAttachmentHTML(attachment, false)).join('')}
                </div>
            </div>
            ` : ''}
        </div>
    `;
}

/**
 * Generate type-specific fields for events
 */
function generateEventTypeSpecificFields(event: CarEvent): string {
  const fields: string[] = [];

  if (event.type === 'fuel' && event.fuel) {
    const fuel = event.fuel;
    if (fuel.liters) fields.push(`<strong>Volume:</strong> ${fuel.liters}L`);
    if (fuel.totalAmount) fields.push(`<strong>Cost:</strong> $${fuel.totalAmount.toFixed(2)}`);
    if (fuel.station) fields.push(`<strong>Station:</strong> ${escapeHtml(fuel.station)}`);
  }

  if (event.type === 'service' && event.service) {
    const service = event.service;
    if (service.workshop) fields.push(`<strong>Workshop:</strong> ${escapeHtml(service.workshop)}`);
    if (service.cost) fields.push(`<strong>Cost:</strong> $${service.cost.toFixed(2)}`);
    if (service.nextDueMileage) fields.push(`<strong>Next Service:</strong> ${service.nextDueMileage.toLocaleString()} km`);
    if (service.nextDueAt) fields.push(`<strong>Next Service Date:</strong> ${new Date(service.nextDueAt).toLocaleDateString()}`);
  }

  if (event.type === 'tires' && event.tires) {
    const tires = event.tires;
    if (tires.brand) fields.push(`<strong>Brand:</strong> ${escapeHtml(tires.brand)}`);
    if (tires.size) fields.push(`<strong>Size:</strong> ${escapeHtml(tires.size)}`);
    if (tires.position) fields.push(`<strong>Position:</strong> ${escapeHtml(tires.position)}`);
    if (tires.price) fields.push(`<strong>Price:</strong> $${tires.price.toFixed(2)}`);
  }

  if (event.type === 'obd' && event.obd) {
    const obd = event.obd;
    if (obd.source) fields.push(`<strong>Source:</strong> ${escapeHtml(obd.source)}`);
    if (obd.fileName) fields.push(`<strong>File:</strong> ${escapeHtml(obd.fileName)}`);
  }

  return fields.length > 0 ? `
        <div class="event-details">
            ${fields.map(field => `<div class="detail-row">${field}</div>`).join('')}
        </div>
    ` : '';
}

/**
 * Generate attachment HTML
 */
function generateAttachmentHTML(attachment: Attachment, isLarge: boolean = false): string {
  const sizeClass = isLarge ? 'attachment-large' : 'attachment-small';
  
  if (attachment.type === 'image' && attachment.url) {
    return `
        <div class="attachment ${sizeClass}">
            <img src="${attachment.url}" alt="${escapeHtml(attachment.name)}" />
            <p class="attachment-name">${escapeHtml(attachment.name)}</p>
        </div>
    `;
  }
  
  return `
        <div class="attachment ${sizeClass}">
            <div class="attachment-icon">📄</div>
            <p class="attachment-name">${escapeHtml(attachment.name)}</p>
            ${attachment.size ? `<p class="attachment-size">${formatFileSize(attachment.size)}</p>` : ''}
        </div>
    `;
}

/**
 * Generate summary section
 */
function generateSummarySection(events: CarEvent[]): string {
  const eventCounts = events.reduce((acc, event) => {
    acc[event.type] = (acc[event.type] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const totalEvents = events.length;
  const latestEvent = events.length > 0 
    ? events.sort((a, b) => new Date(b.occurredAt).getTime() - new Date(a.occurredAt).getTime())[0]
    : null;

  return `
        <section class="summary-section">
            <h2>Summary</h2>
            <div class="summary-grid">
                <div class="summary-item">
                    <strong>Total Events:</strong> ${totalEvents}
                </div>
                ${latestEvent ? `
                <div class="summary-item">
                    <strong>Latest Event:</strong> ${escapeHtml(latestEvent.title)} (${new Date(latestEvent.occurredAt).toLocaleDateString()})
                </div>
                ` : ''}
                <div class="summary-item">
                    <strong>Event Breakdown:</strong>
                    <ul>
                        ${Object.entries(eventCounts).map(([type, count]) => 
                            `<li>${escapeHtml(type)}: ${count}</li>`
                        ).join('')}
                    </ul>
                </div>
            </div>
        </section>
    `;
}

/**
 * Get CSS styles for export
 */
function getExportCSS(): string {
  return `
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            background: white;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 20px;
        }

        .header h1 {
            font-size: 2rem;
            color: #1f2937;
            margin-bottom: 10px;
        }

        .export-date {
            color: #6b7280;
            font-size: 0.9rem;
        }

        .vehicle-section, .events-section, .summary-section {
            margin-bottom: 40px;
        }

        .vehicle-section h2, .events-section h2, .summary-section h2 {
            font-size: 1.5rem;
            color: #1f2937;
            margin-bottom: 20px;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 10px;
        }

        .vehicle-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 30px;
        }

        .vehicle-details .detail-row {
            margin-bottom: 10px;
            padding: 8px 0;
            border-bottom: 1px solid #f3f4f6;
        }

        .photo-grid, .attachment-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
            margin-top: 15px;
        }

        .attachment {
            text-align: center;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 10px;
        }

        .attachment img {
            max-width: 100%;
            height: auto;
            border-radius: 4px;
        }

        .attachment-large img {
            max-height: 200px;
        }

        .attachment-small img {
            max-height: 100px;
        }

        .attachment-name {
            font-size: 0.8rem;
            margin-top: 5px;
            word-break: break-word;
        }

        .attachment-size {
            font-size: 0.7rem;
            color: #6b7280;
        }

        .attachment-icon {
            font-size: 2rem;
            margin-bottom: 5px;
        }

        .events-list {
            display: grid;
            gap: 20px;
        }

        .event-card {
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 20px;
            background: #fafafa;
        }

        .event-header {
            display: flex;
            align-items: center;
            gap: 15px;
            margin-bottom: 15px;
        }

        .event-type {
            color: white;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 0.8rem;
            font-weight: 600;
            text-transform: uppercase;
        }

        .event-date, .event-mileage {
            font-size: 0.9rem;
            color: #6b7280;
        }

        .event-title {
            font-size: 1.2rem;
            margin-bottom: 10px;
            color: #1f2937;
        }

        .event-notes {
            margin-bottom: 15px;
            color: #4b5563;
        }

        .event-tags {
            margin-bottom: 15px;
        }

        .tag {
            display: inline-block;
            background: #e5e7eb;
            color: #374151;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 0.8rem;
            margin-right: 8px;
            margin-bottom: 4px;
        }

        .event-details {
            margin-bottom: 15px;
            padding: 15px;
            background: white;
            border-radius: 6px;
        }

        .event-attachments h4 {
            margin-bottom: 10px;
            color: #374151;
        }

        .summary-grid {
            display: grid;
            gap: 15px;
        }

        .summary-item {
            padding: 15px;
            background: #f9fafb;
            border-radius: 6px;
        }

        .summary-item ul {
            margin-top: 10px;
            margin-left: 20px;
        }

        .no-data {
            color: #6b7280;
            font-style: italic;
            text-align: center;
            padding: 40px;
        }

        .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            color: #6b7280;
            font-size: 0.8rem;
        }

        /* Print styles */
        @media print {
            .container {
                max-width: none;
                margin: 0;
                padding: 15px;
            }

            .vehicle-grid {
                grid-template-columns: 1fr;
            }

            .photo-grid, .attachment-grid {
                grid-template-columns: repeat(3, 1fr);
            }

            .event-card {
                break-inside: avoid;
                margin-bottom: 15px;
            }

            .attachment img {
                max-height: 120px;
            }
        }

        @page {
            margin: 1in;
        }
    `;
}

/**
 * Utility functions
 */
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`;
}

/**
 * Download HTML as file
 */
export function downloadHTML(html: string, filename: string = 'vehicle-sale-pack.html'): void {
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
}

/**
 * Open HTML in new window for printing
 */
export function printHTML(html: string): void {
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    
    // Wait for content to load, then print
    setTimeout(() => {
      printWindow.print();
    }, 500);
  }
}